function f(){this.o=0}function aa(){this.o=0;this.za=this.ka=null;this.Ma=this.La=0}function ba(){this.Ja=this.Ka=this.Da=this.Y=this.o=0;this.F=null}function ca(){g.call(this);this.$=0}function h(){da.call(this);this.pa=0}function ea(){fa.call(this);this.Fa=null}function ha(){this.o=0;this.h=null;this.i=0}function ia(){this.o=0;this.V=this.T=null}function ja(){ea.call(this);this.Ta=0;this.Wa=this.Ua=this.lb=null}function ka(){la.call(this);this.oa=null}
function ma(){this.Aa=this.L=this.o=0;this.P=this.Ga=this.H=this.v=null}function na(){ia.call(this);this.ma=0;this.D=null}function oa(){this.o=0;this.ea=null}function pa(){oa.call(this);this.R=0;this.j=null;this.ba=this.ja=this.J=0}function qa(){ca.call(this);this.m=null;this.U=0}function ra(){this.o=0;this.K=this.la=null}
var sa=2463534242,m=a=>function(){return a(this)},p=a=>function(b){return a(this,b)},r=a=>function(b,c){return a(this,b,c)},t=a=>function(b,c,d){return a(this,b,c,d,d)},u=a=>a.Xa=()=>{},v=a=>{if(0===a)return function(){};void 0===a&&(a=f);return function(){a.call(this)}},w=(a,b)=>{let c={m:null,ca:null,l:{ua:[],W:null}};c.l.Oa=!0;c.l.name=a;c.l.qa=b;c.l.Na=!1;c.l.item=null;c.l.ta=null;c.l.ra=null;c.l.sa=null;return c},ta=w("boolean","Z"),ua=w("char","C"),va=w("byte","B"),wa=w("short","S"),xa=w("int",
"I"),ya=w("long","J"),za=w("float","F"),Aa=w("double","D"),Ba=w("void","V"),x=new ArrayBuffer(16);new DataView(x);new Float32Array(x);new Float64Array(x);new Int32Array(x);new BigInt64Array(x);
var y=Math.imul||function(a,b){let c=a&65535,d=b&65535;return c*d+((a>>>16&65535)*d+c*(b>>>16&65535)<<16>>>0)|0},Ca=(a,b)=>{a>>>=0;b>>>=0;return a<b?-1:a>b?1:0},A=(a,b)=>{b=Array(b);b.fill(null);return new (z(a))(b)},z=a=>{var b=a.m;if(null===b){function c(d){this.o=0;this.data=d}c.prototype=Object.create(f.prototype);c.prototype.type=a;c.prototype.constructor=c;c.prototype.toString=function(){let d="[";for(let e=0;e<this.data.length;++e)0<e&&(d+=", "),d+=this.data[e].toString();return d+"]"};b="["+
a.l.qa;c.l={item:a,ua:[f],Oa:!1,W:f,name:b,qa:b,Na:!1,ta:null,ra:null,sa:null};c.ca=null;c.m=null;b=c;a.m=c}return b},Da=(a,b,c)=>{let d="";for(c=b+c;b<c;b=b+1024|0)d+=String.fromCharCode.apply(null,a.subarray(b,Math.min(c,b+1024|0)));return d},C=a=>null===a?null:B(a),D=Symbol("javaException"),F=a=>{var b=a.Ca;if(!b&&(b=Ea(a),b=null!==b?b.Ca:void 0,b=new E("Java exception thrown","object"===typeof b?{cause:b}:void 0),"function"===typeof Error.captureStackTrace&&Error.captureStackTrace(b),b[D]=a,a.Ca=
b,"function"===typeof $rt_decodeStack&&b.stack)){a=$rt_decodeStack(b.stack);A(f,a.length);for(let c=0;c<a.length;){a=a[c];C(a.className);C(a.methodName);C(a.fileName);break}}return b};let E;
if("object"===typeof Reflect){let a=Symbol("defaultMessage");E=function e(c,d){d=Reflect.construct(Error,[void 0,d],e);Object.setPrototypeOf(d,e.prototype);d[a]=c;return d};E.prototype=Object.create(Error.prototype,{constructor:{configurable:!0,writable:!0,value:E},message:{get(){try{let c=this[D];if("object"===typeof c){let d=c.ka;if("object"===typeof d)return null!==d?d.toString():null}return this[a]}catch(c){return"Exception occurred trying to extract Java exception message: "+c}}}})}else E=Error;
var Fa=a=>{let b="";return c=>{let d=0;for(;;){let e=c.indexOf("\n",d);if(0>e)break;a(b+c.substring(d,e));b="";d=e+1}b+=c.substring(d)}},Ga="function"===typeof $rt_putStdoutCustom?$rt_putStdoutCustom:"object"===typeof console?Fa(a=>console.info(a)):()=>{},Ha=null,G=a=>{let b=0,c=Array(a.length);for(let d=0;d<a.length;++d){let e=a[b++];c[d]=(0<=e?c[e]:"")+a[b++]+"."}Ha=c},H=a=>{let b=Ha,c=0;for(;c<a.length;){let l=a[c++];l.l={};var d=l.l,e=a[c++];d.name=0!==e?e:null;null!==d.name&&(e=a[c++],0<=e&&
(d.name=b[e]+d.name));d.qa="L"+d.name+";";e=a[c++];d.W=0!==e?e:null;d.ua=a[c++];d.W?(d.ua.push(d.W),l.prototype=Object.create(d.W.prototype)):l.prototype={};e=a[c++];d.Na=0!==(e&8);d.flags=e;d.Oa=!1;d.item=null;l.prototype.constructor=l;l.ca=null;d.Ob=a[c++];e=a[c++];if(0===e)d.ta=null,d.ra=null,d.sa=null;else{var k=e[0];d.sa=0!==k?k:null;k=e[1];d.ra=0!==k?k:null;e=e[2];d.ta=0!==e?e:null}d=a[c++];l.Xa=0!==d?d:function(){};d=a[c++];if(0!==d)for(e=0;e<d.length;e+=2){k=d[e];let n=d[e+1];"function"===
typeof k&&(k=[k]);for(let q=0;q<k.length;++q)k[q](l.prototype,n)}l.m=null}},Ia=(a,b)=>{let c;try{c=a()}catch(d){c=d}if("undefined"!==typeof b)b(c);else if(c instanceof Error)throw c;},Oa=a=>{let b;b=Ja(I(a.constructor));a=Ka(a);J();{var c,d;let k,l;if(a){J();if(a){var e=0;(c=a>>>16|0)?e=16:c=a;(d=c>>>8|0)?e|=8:d=c;(c=d>>>4|0)?e|=4:c=d;(d=c>>>2|0)?e|=2:d=c;d>>>1|0&&(e|=1);e=(32-e|0)-1|0}else e=32;c=(((32-e|0)+4|0)-1|0)/4|0;e=new K(new Uint16Array(c));c=y(c-1|0,4);for(d=0;0<=c;)k=e.data,l=d+1|0,k[d]=
La((a>>>c|0)&15,16),c=c-4|0,d=l;a=Ma(e)}else a=B("0")}e=L();M(Na(M(e,b),64),a);return N(e.h,e.i)},Ka=a=>{if(!a.o){let b=sa;b^=b<<13;b^=b>>>17;sa=b^=b<<5;a.o=b}return a.o},Pa=v();let O=a=>{a.La=1;a.Ma=1;a.Ba()},P=(a,b)=>{a.La=1;a.Ma=1;a.Ba();a.ka=b};var Ea=a=>a.za===a?null:a.za,Qa=v(aa),Q=v(Qa),R=v(Q),Ra=()=>{let a=new R;O(a);return a},Sa=v(),Ta=v(),Ua=v();let Va=null;var Wa=v(0),Xa=(a,b)=>{a.F=b;a.Da=a.F.$;a.Ka=a.F.aa();a.Ja=-1},Ya=v(0),S=v(0),g=v(),Za=v(0),$a=v(0),T=v(0),da=v(),U=v(0);
let V=null,J=()=>{J=u(h);I(xa)};var ab=a=>{let b=new h;J();b.pa=a;return b},bb=a=>{J();if(-128<=a&&127>=a){let b;J();a:if(null===V)for(V=A(h,256),b=0;;){if(b>=V.data.length)break a;V.data[b]=ab(b-128|0);b=b+1|0}return V.data[a+128|0]}return ab(a)},cb=v(0),db=v(Q),eb=v();let W=()=>{W=u(eb);I(ua);A(eb,128)};
var La=(a,b)=>{W();return 2<=b&&36>=b&&0<=a&&a<b?10>a?(48+a|0)&65535:((97+a|0)-10|0)&65535:0},fb=v(),gb=v(0),hb=v(0),ib=(a,b,c)=>{a.Ya(b)&&(c=a.bb(b));return c},jb=v(),kb=(a,b)=>{a>b&&(b=a);return b},lb=v(0),mb=v(),nb=v(0),ob=v(0),pb=v(R),qb=()=>{let a=new pb;O(a);return a},rb=v(0),sb=v(0),fa=v(),tb=v(),ub=v(0),vb=(a,b,c)=>{let d,e,k;if(0<=b&&b<=a.i){if(null===c)c=C("null");else if(c.ia())return a;a.S(a.i+c.B()|0);for(d=a.i-1|0;d>=b;)a.h.data[d+c.B()|0]=a.h.data[d],d=d+-1|0;a.i=a.i+c.B()|0;for(d=
0;d<c.B();)e=a.h.data,k=b+1|0,e[b]=c.Va(d),d=d+1|0,b=k;return a}a=qb();throw F(a);},xb=(a,b,c)=>{wb(a,b,b+1|0);a.h.data[b]=c;return a},yb=(a,b,c)=>a.Z(b,null===c?C("null"):c.M()),zb=(a,b)=>{if(!(a.h.data.length>=b)){var c=1073741823<=a.h.data.length?2147483647:kb(b,kb(2*a.h.data.length|0,5));let e;b=a.h.data;e=new K(new Uint16Array(c));var d=b.length;c<d&&(d=c);c=d;for(d=0;d<c;)e.data[d]=b[d],d=d+1|0;a.h=e}};
let wb=(a,b,c)=>{var d=a.i-b|0;a.S((a.i+c|0)-b|0);for(d=d-1|0;0<=d;)a.h.data[c+d|0]=a.h.data[b+d|0],d=d+-1|0;a.i=a.i+(c-b|0)|0};
var Ab=v(0),Bb=v(ha),L=()=>{let a=new Bb;a.h=new K(new Uint16Array(16));return a},M=(a,b)=>{a.ga(a.i,b);return a},Na=(a,b)=>{a.ha(a.i,b);return a},Cb=v(Q),Db=()=>{let a=new Cb;O(a);return a},Eb=v(0),Fb=(a,b,c,d)=>{a.Fa=b;a.lb=L();a.Ua=new K(new Uint16Array(32));a.Ta=c;a.Wa=d},Gb=v(ja),Hb=v(Gb),la=v(g),Ib=(a,b)=>{a.P=b;a.Aa=b.J;a.v=null},Jb=a=>{if(a.Aa!=a.P.J)throw a=Db(),F(a);},Lb=a=>{let b,c;Jb(a);if(!a.A())throw a=new Kb,O(a),F(a);null===a.v?(b=a.P.j.data,c=a.L,a.L=c+1|0,a.H=b[c],a.v=a.H.D,a.Ga=
null):(null!==a.H&&(a.Ga=a.H),a.H=a.v,a.v=a.v.D)},Mb=v(ma),Nb=(a,b,c)=>{a.T=b;a.V=null;a.ma=c},Pb=()=>{let a=new pa;Ob(a,16,.75);return a};let Qb=a=>{if(1073741824<=a)return 1073741824;if(!a)return 16;a=a-1|0;a|=a>>1;a|=a>>2;a|=a>>4;a|=a>>8;return(a|a>>16)+1|0};
var Ob=(a,b,c)=>{if(0<=b&&0<c)b=Qb(b),a.R=0,a.j=a.Ea(b),a.ja=c,a.ba=a.j.data.length*a.ja|0;else throw a=Rb(),F(a);},Ub=(a,b)=>{let c,d;null===b?a=Sb(a):(c=b.X(),d=c&(a.j.data.length-1|0),a=Tb(a,b,d,c));return a},Tb=(a,b,c,d)=>{for(a=a.j.data[c];null!==a&&(a.ma!=d||!Vb(b,a.T));)a=a.D;return a},Sb=a=>{for(a=a.j.data[0];null!==a&&null!==a.T;)a=a.D;return a};let Wb=(a,b,c,d)=>{let e=new na;Nb(e,b,d);e.D=a.j.data[c];return a.j.data[c]=e};
var Vb=(a,b)=>a===b||a.Za(b)?1:0,Xb=v(Q),Yb=v(0),Zb=(a,b)=>{if(0<=b)a.m=A(f,b);else throw a=Rb(),F(a);},$b=a=>{let b=new qa;Zb(b,a);return b},ac=v(),bc=v(),cc=v(0),dc=v(),X=v();let Y=()=>{Y=u(X);new K(new Uint16Array(0));let a=new X;Y();a.s="";new dc};var ec=(a,b)=>{Y();a.s=Da(b.data,0,b.data.length)},Ma=a=>{let b=new X;ec(b,a);return b};let B=a=>{let b=new X;b.s=a;return b};
var fc=(a,b,c,d)=>{Y();if(!(0<=c&&0<=d&&d<=(b.data.length-c|0)))throw a=Ra(),F(a);a.s=Da(b.data,c,d)},N=(a,b)=>{let c=new X;fc(c,a,0,b);return c},gc=a=>{Y();return L().Sa(a).M()},Kb=v(Q),hc=v(Q),ic=v(Q),Rb=()=>{let a=new ic;O(a);return a},I=a=>{if(null===a)return null;var b=a.ca;if(null===b){let c=new ra;b=c;b.K=a;a.ca=b;b=c}return b},Ja=a=>{null===a.la&&(a.la=C(a.K.l.name));return a.la};G([-1,"java",0,"lang"]);
H([f,"Object",1,0,[],0,3,0,0,[(a,b)=>a.Hb=b,m(a=>I(a.constructor)),(a,b)=>a.M=b,m(Oa),(a,b)=>a.Mb=b,m(Ka)],Pa,0,f,[],0,0,0,0,0,aa,0,f,[],0,3,0,0,[(a,b)=>a.Ba=b,m(a=>a),(a,b)=>a.Jb=b,m(a=>a.ka),(a,b)=>a.Gb=b,m(Ea)],Qa,0,aa,[],0,3,0,0,[(a,b)=>a.g=b,m(a=>{O(a)}),(a,b)=>a.wa=b,p((a,b)=>{P(a,b)})],Q,0,Qa,[],0,3,0,0,[(a,b)=>a.g=b,m(a=>{O(a)}),(a,b)=>a.wa=b,p((a,b)=>{P(a,b)})],R,0,Q,[],0,3,0,0,[(a,b)=>a.g=b,m(a=>{O(a)})],Sa,0,f,[],0,3,0,0,0,Ta,0,f,[],4,3,0,0,0,Ua,0,f,[],4,3,0,0,0,Wa,0,f,[],3,3,0,0,0,ba,
0,f,[Wa],0,0,0,0,[(a,b)=>a.rb=b,p(Xa),(a,b)=>a.A=b,m(a=>a.Y>=a.Ka?0:1),(a,b)=>a.C=b,m(a=>{let b,c;if(!(a.Da>=a.F.$))throw a=Db(),F(a);a.Ja=a.Y;b=a.F;c=a.Y;a.Y=c+1|0;return b.ab(c)})],Ya,0,f,[],3,3,0,0,0,S,0,f,[Ya],3,3,0,0,0,g,0,f,[S],1,3,0,0,[(a,b)=>a.g=b,m(()=>{}),(a,b)=>a.ia=b,m(a=>a.aa()?0:1)],Za,0,f,[S],3,3,0,0,0,$a,0,f,[Za],3,3,0,0,0,ca,0,g,[$a],1,3,0,0,[(a,b)=>a.g=b,m(()=>{}),(a,b)=>a.I=b,m(a=>{let b=new ba;Xa(b,a);return b})],T,0,f,[],3,3,0,0,0,da,0,f,[T],1,3,0,0,[(a,b)=>a.g=b,m(()=>{})],U,
0,f,[],3,3,0,0,0,h,0,da,[U],0,3,0,J,[(a,b)=>a.da=b,p((a,b)=>{J();a.pa=b}),(a,b)=>a.X=b,m(a=>{a=a.pa;J();return a})],cb,0,f,[],3,3,0,0,0,db,0,Q,[],0,3,0,0,[(a,b)=>a.g=b,m(a=>{O(a)})],eb,0,f,[U],0,3,0,W,0,fb,0,f,[],4,3,0,0,0,gb,0,f,[],3,3,0,0,0,hb,0,f,[],3,3,0,0,[(a,b)=>a.fa=b,r(ib)],jb,0,f,[],4,3,0,0,0,lb,0,f,[],3,3,0,0,0,mb,0,f,[],4,3,0,0,0,nb,0,f,[],3,3,0,0,0,ob,0,f,[S],3,3,0,0,0,pb,0,R,[],0,3,0,0,[(a,b)=>a.g=b,m(a=>{O(a)})],rb,0,f,[cb],3,3,0,0,0,sb,0,f,[],3,3,0,0,0,fa,0,f,[rb,sb],1,3,0,0,[(a,b)=>
a.g=b,m(()=>{})],ea,0,fa,[],0,3,0,0,[(a,b)=>a.tb=b,p((a,b)=>{a.Fa=b})],tb,0,f,[],4,3,0,0,0,ub,0,f,[],3,3,0,0,0,ha,0,f,[T,nb],0,0,0,0,[(a,b)=>a.g=b,m(a=>{a.h=new K(new Uint16Array(16))}),(a,b)=>a.da=b,p((a,b)=>{a.h=new K(new Uint16Array(b))}),(a,b)=>a.Bb=b,p((a,b)=>a.ga(a.i,b)),(a,b)=>a.u=b,p((a,b)=>a.Z(a.i,b)),(a,b)=>a.Z=b,r(vb),(a,b)=>a.yb=b,p((a,b)=>a.ya(b,10)),(a,b)=>a.ya=b,r((a,b,c)=>a.fb(a.i,b,c)),(a,b)=>a.fb=b,t((a,b,c,d)=>{var e;let k,l,n;var q=1;0>c&&(q=0,c=-c|0);a:if(0>Ca(c,d))q?wb(a,b,b+
1|0):(wb(a,b,b+2|0),q=a.h.data,q[b]=45,b=b+1|0),a.h.data[b]=La(c,d);else{k=e=1;l=4294967295/(d>>>0)>>>0;b:for(;;){n=y(e,d);if(0<Ca(n,c)){n=e;break b}k=k+1|0;if(0<Ca(n,l))break;e=n}q||(k=k+1|0);wb(a,b,b+k|0);q?e=b:(q=a.h.data,e=b+1|0,q[b]=45);for(;;){if(!n)break a;q=a.h.data;b=e+1|0;q[e]=La((c>>>0)/(n>>>0)>>>0,d);c=(c>>>0)%(n>>>0)>>>0;n=(n>>>0)/(d>>>0)>>>0;e=b}}return a}),(a,b)=>a.xb=b,p((a,b)=>a.ha(a.i,b)),(a,b)=>a.ha=b,r(xb),(a,b)=>a.ga=b,r(yb),(a,b)=>a.S=b,p(zb),(a,b)=>a.M=b,m(a=>N(a.h,a.i))],Ab,
0,f,[],3,3,0,0,0,Bb,0,ha,[Ab],0,3,0,0,[(a,b)=>a.g=b,m(a=>{a.h=new K(new Uint16Array(16))}),(a,b)=>a.Ab=b,p(M),(a,b)=>a.zb=b,p((a,b)=>{a.Z(a.i,b);return a}),(a,b)=>a.Sa=b,p((a,b)=>{a.ya(b,10);return a}),(a,b)=>a.wb=b,p(Na),(a,b)=>a.cb=b,r((a,b,c)=>{yb(a,b,c);return a}),(a,b)=>a.eb=b,r((a,b,c)=>{xb(a,b,c);return a}),(a,b)=>a.gb=b,r((a,b,c)=>{vb(a,b,c);return a}),(a,b)=>a.M=b,m(a=>N(a.h,a.i)),(a,b)=>a.S=b,p((a,b)=>{zb(a,b)}),(a,b)=>a.ga=b,r((a,b,c)=>a.cb(b,c)),(a,b)=>a.ha=b,r((a,b,c)=>a.eb(b,c)),(a,
b)=>a.Z=b,r((a,b,c)=>a.gb(b,c))],ia,0,f,[gb,lb],0,0,0,0,[(a,b)=>a.ub=b,r((a,b,c)=>{a.T=b;a.V=c})],Cb,0,Q,[],0,3,0,0,[(a,b)=>a.g=b,m(a=>{O(a)})],Eb,0,f,[],3,3,0,0,0,ja,0,ea,[Ab],0,3,0,0,[(a,b)=>a.mb=b,t(Fb)],Gb,0,ja,[],1,3,0,0,[(a,b)=>a.g=b,m(a=>{Fb(a,null,0,null)}),(a,b)=>a.ib=b,p((a,b)=>{a.Ha(b);a.Ha(B("\n"))})],Hb,0,Gb,[],0,3,0,0,[(a,b)=>a.g=b,m(a=>{Fb(a,null,0,null)}),(a,b)=>a.Ha=b,p((a,b)=>{null===b&&(b=C("null"));Ga(null===b?null:b.s)})],la,0,g,[ob],1,3,0,0,[(a,b)=>a.g=b,m(()=>{})],ka,0,la,[],
0,0,0,0,[(a,b)=>a.va=b,p((a,b)=>{a.oa=b}),(a,b)=>a.I=b,m(a=>{a=a.oa;let b=new Mb;Ib(b,a);return b})]]);
H([ma,0,f,[],0,0,0,0,[(a,b)=>a.va=b,p(Ib),(a,b)=>a.A=b,m(a=>{if(null!==a.v)return 1;for(;a.L<a.P.j.data.length;){if(null!==a.P.j.data[a.L])return 1;a.L=a.L+1|0}return 0}),(a,b)=>a.Cb=b,m(Jb),(a,b)=>a.Nb=b,m(Lb)],Mb,0,ma,[Wa],0,0,0,0,[(a,b)=>a.va=b,p((a,b)=>{Ib(a,b)}),(a,b)=>a.C=b,m(a=>{Lb(a);return a.H.T})],na,0,ia,[],0,0,0,0,[(a,b)=>a.ob=b,r(Nb)],oa,0,f,[hb],1,3,0,0,[(a,b)=>a.fa=b,r(ib),(a,b)=>a.g=b,m(()=>{})],pa,0,oa,[lb,T],0,3,0,0,[(a,b)=>a.fa=b,r(ib),(a,b)=>a.Ea=b,p((a,b)=>A(na,b)),(a,b)=>a.g=
b,m(a=>{Ob(a,16,.75)}),(a,b)=>a.da=b,p((a,b)=>{Ob(a,b,.75)}),(a,b)=>a.nb=b,r(Ob),(a,b)=>a.Ya=b,p((a,b)=>null===Ub(a,b)?0:1),(a,b)=>a.bb=b,p((a,b)=>{a=Ub(a,b);return null===a?null:a.V}),(a,b)=>a.Db=b,p(Ub),(a,b)=>a.Eb=b,t(Tb),(a,b)=>a.Fb=b,m(Sb),(a,b)=>a.hb=b,m(a=>{if(null===a.ea){let b=new ka;b.oa=a;a.ea=b}return a.ea}),(a,b)=>a.na=b,r((a,b,c)=>{let d,e,k;null===b?(d=Sb(a),null===d&&(a.J=a.J+1|0,d=Wb(a,null,0,0),b=a.R+1|0,a.R=b,b>a.ba&&a.Ia())):(e=b.X(),k=e&(a.j.data.length-1|0),d=Tb(a,b,k,e),null===
d&&(a.J=a.J+1|0,d=Wb(a,b,k,e),b=a.R+1|0,a.R=b,b>a.ba&&a.Ia()));a=d.V;d.V=c;return a}),(a,b)=>a.jb=b,p((a,b)=>{let c,d,e,k,l,n;b=Qb(b?b<<1:1);c=a.Ea(b);for(d=0;d<a.j.data.length;){e=a.j.data[d];for(a.j.data[d]=null;null!==e;)k=c.data,l=e.ma&(b-1|0),n=e.D,e.D=k[l],k[l]=e,e=n;d=d+1|0}a.j=c;a.ba=a.j.data.length*a.ja|0}),(a,b)=>a.Ia=b,m(a=>{a.jb(a.j.data.length)})],Xb,0,Q,[],0,3,0,0,0,Yb,0,f,[],3,3,0,0,0,qa,0,ca,[lb,T,Yb],0,3,0,0,[(a,b)=>a.da=b,p(Zb),(a,b)=>a.S=b,p((a,b)=>{if(a.m.data.length<b){var c=
1073741823<=a.m.data.length?2147483647:kb(b,kb(2*a.m.data.length|0,5));var d=a.m;b=d.data;d=I(I(d.constructor).K.l.item);if(null===d)throw a=new db,O(a),F(a);if(d===I(Ba))throw a=Rb(),F(a);if(0>c)throw a=new hc,O(a),F(a);d=A(d.K,c);var e=b.length;c<e&&(e=c);c=e;for(e=0;e<c;)d.data[e]=b[e],e=e+1|0;a.m=d}}),(a,b)=>a.ab=b,p((a,b)=>{if(!(0<=b&&b<a.U))throw a=Ra(),F(a);return a.m.data[b]}),(a,b)=>a.aa=b,m(a=>a.U),(a,b)=>a.xa=b,p((a,b)=>{let c,d;a.S(a.U+1|0);c=a.m.data;d=a.U;a.U=d+1|0;c[d]=b;a.$=a.$+1|
0;return 1})],ac,0,f,[],4,3,0,0,0,bc,0,f,[U],1,3,0,0,0,cc,0,f,[],3,3,0,0,0,dc,0,f,[cc],0,3,0,0,[(a,b)=>a.g=b,m(()=>{})],X,0,f,[T,U,nb],0,3,0,Y,[(a,b)=>a.g=b,m(a=>{Y();a.s=""}),(a,b)=>a.pb=b,p(ec),(a,b)=>a.vb=b,p((a,b)=>{a.s=b}),(a,b)=>a.qb=b,t(fc),(a,b)=>a.Va=b,p((a,b)=>{if(0<=b&&b<a.s.length)return a.s.charCodeAt(b);a=qb();throw F(a);}),(a,b)=>a.B=b,m(a=>a.s.length),(a,b)=>a.ia=b,m(a=>a.s.length?0:1),(a,b)=>a.M=b,m(a=>a)],Kb,0,Q,[],0,3,0,0,[(a,b)=>a.g=b,m(a=>{O(a)})],hc,0,Q,[],0,3,0,0,[(a,b)=>a.g=
b,m(a=>{O(a)})],ic,0,Q,[],0,3,0,0,[(a,b)=>a.g=b,m(a=>{O(a)}),(a,b)=>a.wa=b,p((a,b)=>{P(a,b)})],ra,0,f,[Eb,ub],4,3,0,0,[(a,b)=>a.Lb=b,m(a=>a.K),(a,b)=>a.Kb=b,m(Ja),(a,b)=>a.Ib=b,m(a=>I(a.K.l.item))]]);z(ta);var K=z(ua);z(va);z(wa);z(xa);z(ya);z(za);z(Aa);X.prototype.toString=function(){return null===this?null:this.s};X.prototype.valueOf=X.prototype.toString;f.prototype.toString=function(){var a=Oa(this);return null===a?null:a.s};J();W();Y();function jc(){this.o=0;this.G=null}function kc(){this.O=this.N=this.o=0;this.F=null}var lc=(a,b,c,d)=>{a.F=b;a.N=c;a.O=d},mc=(a,b,c)=>{let d=new kc;lc(d,a,b,c);return d};G([]);
H([jc,0,f,[nc],0,0,0,0,[(a,b)=>a.g=b,m(a=>{a.G=Pb()}),(a,b)=>a.Pa=b,t((a,b,c,d)=>{if(0<=b&&0<=c)a.G.na(mc(a,b,c),d);else throw a=C("Table coordinates can not be negative"),b=new ic,P(b,a),F(b);}),(a,b)=>a.Ra=b,r((a,b,c)=>{a.G.na(mc(a,-1,b),c)}),(a,b)=>a.Qa=b,r((a,b,c)=>{a.G.na(mc(a,b,-1),c)}),(a,b)=>a.$a=b,m(a=>{var b,c;let d,e,k;var l=b=-1;for(c=a.G.hb().I();c.A();){var n=c.C();n.N>b&&(b=n.N);n.O>l&&(l=n.O)}b=b+1|0;l=l+1|0;c=$b(l);for(n=-1;n<l;){d=$b(b);for(e=-1;e<b;)k=a.G.fa(mc(a,e,n),B("?")),-1==
e&&-1==n&&(k=B("")),d.xa(k),e=e+1|0;c.xa(d);n=n+1|0}return c})],kc,0,f,[],0,0,0,0,[(a,b)=>a.sb=b,t(lc),(a,b)=>a.Za=b,p((a,b)=>b instanceof kc?a.N==b.N&&a.O==b.O?1:0:0),(a,b)=>a.X=b,m(a=>{var b=A(f,2);var c=b.data;c[0]=bb(a.N);c[1]=bb(a.O);if(null===b)b=0;else{c=1;for(a=0;;){var d=b.data;if(a>=d.length)break;c=31*c|0;d=d[a];d=null!==d?d.X():0;c=c+d|0;a=a+1|0}b=c}return b})]]);var nc=v(0);G([]);H([nc,0,f,[],3,3,0,0,0]);var oc=v();let qc=(a,b,c)=>{let d;d=0;for(a=a.I();a.A();){var e=a.C();1==d&&c.u(C(" | "));var k=c,l=k.u;{var n=void 0;let q;n=b-e.B()|0;0>=n||(q=pc(32,n),n=L(),M(M(n,q),e),e=N(n.h,n.i))}l.call(k,e);d=d+1|0}c.u(B("\n"))},pc=(a,b)=>{b=new K(new Uint16Array(b));var c=b.data.length,d=0;let e,k;if(d>c)throw a=Rb(),F(a);for(;d<c;)e=b.data,k=d+1|0,e[d]=a,d=k;return Ma(b)};G([]);
H([oc,0,f,[],0,3,0,0,[(a,b)=>a.g=b,m(()=>{}),(a,b)=>a.kb=b,p((a,b)=>{var c;let d,e,k;if(b.ia())return B("");var l=a=0;for(c=b.I();c.A();){d=c.C();for(e=d.I();e.A();)k=e.C(),k.B()>l&&(l=k.B());a<d.aa()&&(a=d.aa())}l=l+2|0;c=L();b=b.I();qc(b.C(),l,c);c.u(pc(45,l+1|0));c.u(B("+"));c.u(pc(45,y(a-1|0,l)+1|0));for(c.u(B("\n"));b.A();)qc(b.C(),l,c);return c.M()})]]);var rc=v();let Z=()=>{Z=u(rc)};G([]);H([rc,0,f,[],0,3,0,Z,0]);var sc=(a=>(b,c)=>{b||=[];let d=A(f,b.length);for(let e=0;e<b.length;++e)d.data[e]=C(b[e]);Ia(()=>{a.call(null,d)},c)})(()=>{Z();if(null===Va){var a=new Hb;Fb(a,null,0,null);Va=a}a=Va;var b=a.ib;Z();var c=new jc;c.G=Pb();let d,e;Z();for(d=1;15>d;){for(e=1;15>e;)c.Pa(e,d,gc(y(d,e))),e=e+1|0;c.Qa(d,gc(d));c.Ra(d,gc(d));d=d+1|0}c=(new oc).kb(c.$a());b.call(a,c)});sc.Pb=a=>a instanceof Error&&"object"===typeof a[D]?a[D]:null;Z();sc();
