"use strict";
(function(module){if(typeof define==='function'&&define.amd){define(['exports'],function(exports){module(exports);});}else if(typeof exports==='object'&&exports!==null&&typeof exports.nodeName!=='string'){module(exports);}else{module(typeof self!=='undefined'?self:this);}}(function(B){let Co=2463534242,CX=()=>{let x=Co;x^=x<<13;x^=x>>>17;x^=x<<5;Co=x;return x;},Bi=f=>function(){return f(this);},B3=f=>function(p1){return f(this,p1);},CC=f=>(args,callback)=>{if(!args){args=[];}let javaArgs=Bc(V(),args.length);for
(let i=0;i<args.length;++i){javaArgs.data[i]=R(args[i]);}C4(()=>{f.call(null,javaArgs);},callback);},B1=target=>target.$clinit=()=>{},C$=obj=>{let cls=obj.constructor;let arrayDegree=0;while(cls.$meta&&cls.$meta.item){++arrayDegree;cls=cls.$meta.item;}let clsName="";if(cls.$meta.primitive){clsName=cls.$meta.name;}else {clsName=cls.$meta?cls.$meta.name||"a/"+cls.name:"@"+cls.name;}while(arrayDegree-->0){clsName+="[]";}return clsName;},F=superclass=>{if(superclass===0){return function(){};}if(superclass===void 0)
{superclass=V();}return function(){superclass.call(this);};},Y=cls=>CZ(cls),V=()=>E,Df=()=>{return {$array:null,classObject:null,$meta:{supertypes:[],superclass:null}};},Bh=(name,binaryName)=>{let cls=Df();cls.$meta.primitive=true;cls.$meta.name=name;cls.$meta.binaryName=binaryName;cls.$meta.enum=false;cls.$meta.item=null;cls.$meta.simpleName=null;cls.$meta.declaringClass=null;cls.$meta.enclosingClass=null;return cls;},Cr=Bh("boolean","Z"),Bs=Bh("char","C"),BO=Bh("int","I"),CG=Bh("void","V");
if(typeof BigInt!=='function'){}else if(typeof BigInt64Array!=='function'){}else {}let Di=(a,b)=>a>b?1:a<b? -1:a===b?0:1,BI=Math.imul||function(a,b){let ah=a>>>16&0xFFFF;let al=a&0xFFFF;let bh=b>>>16&0xFFFF;let bl=b&0xFFFF;return al*bl+(ah*bl+al*bh<<16>>>0)|0;},Bw=(a,b)=>(a>>>0)/(b>>>0)>>>0,Dg=(a,b)=>(a>>>0)%(b>>>0)>>>0,BP=(a,b)=>{a>>>=0;b>>>=0;return a<b? -1:a>b?1:0;},Bc=(cls,sz)=>{let data=new Array(sz);data.fill(null);return new (Bk(cls))(data);};
if(typeof BigInt64Array!=='function'){}else {}let G=sz=>new C7(new Uint16Array(sz)),B0=sz=>new Dk(new Int32Array(sz)),Bk=cls=>{let result=cls.$array;if(result===null){function JavaArray(data){(V()).call(this);this.data=data;}JavaArray.prototype=Object.create((V()).prototype);JavaArray.prototype.type=cls;JavaArray.prototype.constructor=JavaArray;JavaArray.prototype.toString=function(){let str="[";for(let i=0;i<this.data.length;++i){if(i>0){str+=", ";}str+=this.data[i].toString();}str+="]";return str;};JavaArray.prototype.S
=function(){let dataCopy;if('slice' in this.data){dataCopy=this.data.slice();}else {dataCopy=new this.data.constructor(this.data.length);for(let i=0;i<dataCopy.length;++i){dataCopy[i]=this.data[i];}}return new (Bk(this.type))(dataCopy);};let name="["+cls.$meta.binaryName;JavaArray.$meta={item:cls,supertypes:[V()],primitive:false,superclass:V(),name:name,binaryName:name,enum:false,simpleName:null,declaringClass:null,enclosingClass:null};JavaArray.classObject=null;JavaArray.$array=null;result=JavaArray;cls.$array
=JavaArray;}return result;},BJ,C3=strings=>{Du();BJ=new Array(strings.length);for(let i=0;i<strings.length;++i){BJ[i]=Ce(R(strings[i]));}},D=index=>BJ[index],W=(array,offset,count)=>{let result="";let limit=offset+count;for(let i=offset;i<limit;i=i+1024|0){let next=Math.min(limit,i+1024|0);result+=String.fromCharCode.apply(null,array.subarray(i,next));}return result;},R=str=>str===null?null:CR(str),N=str=>str===null?null:str.t,Du=()=>(()=>{})(),Ce;
{Ce=str=>str;}let Cx=(obj,cls)=>obj instanceof V()&&!!obj.constructor.$meta&&Bv(obj.constructor,cls),Bv=(from,to)=>{if(from===to){return true;}let map=from.$meta.assignableCache;if(typeof map==='undefined'){map=new Map();from.$meta.assignableCache=map;}let cachedResult=map.get(to);if(typeof cachedResult!=='undefined'){return cachedResult;}if(to.$meta.item!==null){let result=from.$meta.item!==null&&Bv(from.$meta.item,to.$meta.item);map.set(to,result);return result;}let supertypes=from.$meta.supertypes;for(let i
=0;i<supertypes.length;i=i+1|0){if(Bv(supertypes[i],to)){map.set(to,true);return true;}}map.set(to,false);return false;},M=ex=>{throw Dv(ex);},Bo=Symbol("javaException"),Dv=ex=>{let err=ex.$jsException;if(!err){let javaCause=Dq(ex);let jsCause=javaCause!==null?javaCause.$jsException:void 0;let cause=typeof jsCause==="object"?{cause:jsCause}:void 0;err=new T("Java exception thrown",cause);if(typeof Error.captureStackTrace==="function"){Error.captureStackTrace(err);}err[Bo]=ex;ex.$jsException=err;CT(err,ex);}return err;},CT
=(err,ex)=>{if(typeof CO==="function"&&err.stack){let stack=CO(err.stack);let javaStack=Bc(C0(),stack.length);let elem;let noStack=false;for(let i=0;i<stack.length;++i){let element=stack[i];elem=C5(R(element.className),R(element.methodName),R(element.fileName),element.lineNumber);if(elem==null){noStack=true;break;}javaStack.data[i]=elem;}if(!noStack){Dm(ex,javaStack);}}},T;
if(typeof Reflect==='object'){let defaultMessage=Symbol("defaultMessage");T=function T(message,cause){let self=Reflect.construct(Error,[void 0,cause],T);Object.setPrototypeOf(self,T.prototype);self[defaultMessage]=message;return self;}
;T.prototype=Object.create(Error.prototype,{constructor:{configurable:true,writable:true,value:T},message:{get(){try {let javaException=this[Bo];if(typeof javaException==='object'){let javaMessage=Cy(javaException);if(typeof javaMessage==="object"){return javaMessage!==null?javaMessage.toString():null;}}return this[defaultMessage];}catch(e){return "Exception occurred trying to extract Java exception message: "+e;}}}});}else {T=Error;}let CH=e=>e instanceof Error&&typeof e[Bo]==='object'?e[Bo]:null,Cy=t=>Do(t),Dq
=t=>Ds(t),C0=()=>V(),C5=(className,methodName,fileName,lineNumber)=>{{return null;}},Dm=(e,stack)=>{},C8=outputFunction=>{let buffer="";return msg=>{let index=0;while(true){let next=msg.indexOf('\n',index);if(next<0){break;}outputFunction(buffer+msg.substring(index,next));buffer="";index=next+1;}buffer+=msg.substring(index);};},J=typeof $rt_putStdoutCustom==="function"?$rt_putStdoutCustom:typeof console==="object"?C8(msg=>console.info(msg)):()=>{},B2=null,Cz=data=>{let i=0;let packages=new Array(data.length);for
(let j=0;j<data.length;++j){let prefixIndex=data[i++];let prefix=prefixIndex>=0?packages[prefixIndex]:"";packages[j]=prefix+data[i++]+".";}B2=packages;},B7=data=>{let packages=B2;let i=0;while(i<data.length){let cls=data[i++];cls.$meta={};let m=cls.$meta;let className=data[i++];m.name=className!==0?className:null;if(m.name!==null){let packageIndex=data[i++];if(packageIndex>=0){m.name=packages[packageIndex]+m.name;}}m.binaryName="L"+m.name+";";let superclass=data[i++];m.superclass=superclass!==0?superclass:null;m.supertypes
=data[i++];if(m.superclass){m.supertypes.push(m.superclass);cls.prototype=Object.create(m.superclass.prototype);}else {cls.prototype={};}let flags=data[i++];m.enum=(flags&8)!==0;m.flags=flags;m.primitive=false;m.item=null;cls.prototype.constructor=cls;cls.classObject=null;m.accessLevel=data[i++];let innerClassInfo=data[i++];if(innerClassInfo===0){m.simpleName=null;m.declaringClass=null;m.enclosingClass=null;}else {let enclosingClass=innerClassInfo[0];m.enclosingClass=enclosingClass!==0?enclosingClass:null;let declaringClass
=innerClassInfo[1];m.declaringClass=declaringClass!==0?declaringClass:null;let simpleName=innerClassInfo[2];m.simpleName=simpleName!==0?simpleName:null;}let clinit=data[i++];cls.$clinit=clinit!==0?clinit:function(){};let virtualMethods=data[i++];if(virtualMethods!==0){for(let j=0;j<virtualMethods.length;j+=2){let name=virtualMethods[j];let func=virtualMethods[j+1];if(typeof name==='string'){name=[name];}for(let k=0;k<name.length;++k){cls.prototype[name[k]]=func;}}}cls.$array=null;}},C4=(runner,callback)=>{let result;try {result
=runner();}catch(e){result=e;}if(typeof callback!=='undefined'){callback(result);}else if(result instanceof Error){throw result;}};
function E(){this.$id$=0;}
let Cb=a=>{return;},DJ=()=>{let a=new E();Cb(a);return a;},Dx=a=>{let b,c;b=a.constructor;if(b===null)c=null;else{c=b.classObject;if(c===null){c=new U;c.D=b;b.classObject=c;}}return c;},Dh=a=>{let b,c,d,e,f,g,h,i,j;b=a;if(!b.$id$)b.$id$=CX();c=CY(a.$id$,4);b=new K;b.u=G(16);d=b.v;e=b;f=D(0);e=e;Z(e,d,f);Z(e,b.v,c===null?D(1):c);f=new H;g=b.u;h=g.data;i=b.v;j=h.length;if(i>=0&&i<=(j-0|0)){f.t=W(g.data,0,i);return f;}b=new S;b.A=1;b.z=1;M(b);},BR=F(0),BZ=F(0);
function U(){let a=this;E.call(a);a.G=null;a.D=null;}
let CZ=b=>{let c;if(b===null)return null;c=b.classObject;if(c===null){c=new U;c.D=b;b.classObject=c;}return c;},DD=a=>{let b,c;b=a.D.$meta.item;if(b===null)c=null;else{c=b.classObject;if(c===null){c=new U;c.D=b;b.classObject=c;}}return c;},CU=F(),Db=F();
function Bg(){let a=this;E.call(a);a.J=null;a.O=null;a.A=0;a.z=0;}
let B_=a=>{a.A=1;a.z=1;},DE=()=>{let a=new Bg();B_(a);return a;},DI=a=>{return a;},Do=a=>{return a.J;},Ds=a=>{let b;b=a.O;if(b===a)b=null;return b;},Bn=F(Bg),Cs=a=>{a.A=1;a.z=1;},Dy=()=>{let a=new Bn();Cs(a);return a;},P=F(Bn),BT=a=>{a.A=1;a.z=1;},DB=()=>{let a=new P();BT(a);return a;},CL=(a,b)=>{a.A=1;a.z=1;a.J=b;},DG=a=>{let b=new P();CL(b,a);return b;},Dr=F(P),Ba=F(0),Bd=F(0),BH=F(0),H=F(),BV=null,Cj=null,Ca=null,CE=(a,b)=>{a.t=W(b.data,0,b.data.length);},DA=a=>{let b=new H();CE(b,a);return b;},CV=(a,b)=>
{a.t=b;},CR=a=>{let b=new H();CV(b,a);return b;},C_=(a,b)=>{let c,d,e,f,g;if(a===b)return 0;c=a.t.length;d=b.t.length;if(c<d)d=c;e=0;a:{b:{while(true){if(e>=d)return a.t.length-b.t.length|0;if(e<0)break a;if(e>=a.t.length)break a;f=a.t.charCodeAt(e);if(Bb===null){if(X===null)X=Ck();Bb=B8(Cv((X.value!==null?R(X.value):null)));}g=Cp(Bb,f)&65535;if(e<0)break b;if(e>=b.t.length)break b;f=b.t.charCodeAt(e);if(Bb===null){if(X===null)X=Ck();Bb=B8(Cv((X.value!==null?R(X.value):null)));}f=g-(Cp(Bb,f)&65535)|0;if(f)break;e
=e+1|0;}return f;}b=new Be;b.A=1;b.z=1;M(b);}b=new Be;b.A=1;b.z=1;M(b);},Dc=a=>{return a;},DH=()=>{let b;BV=G(0);b=new H;b.t="";Cj=b;Ca=new Bq;},By=F(),C2=F(By),Cg=null,Dj=b=>{let c,d;if(!b)return 32;c=0;d=b>>>16|0;if(d)c=16;else d=b;b=d>>>8|0;if(!b)b=d;else c=c|8;d=b>>>4|0;if(!d)d=b;else c=c|4;b=d>>>2|0;if(!b)b=d;else c=c|2;if(b>>>1|0)c=c|1;return (32-c|0)-1|0;},DF=()=>{Cg=Y(BO);};
function Bm(){let a=this;E.call(a);a.u=null;a.v=0;}
let Z=(a,b,c)=>{let d,e,f,g;if(b>=0&&b<=a.v){if(c===null)c=D(1);else if(c.t.length?0:1)return a;d=a.v+c.t.length|0;Bx(a,d);e=a.v-1|0;while(e>=b){a.u.data[e+c.t.length|0]=a.u.data[e];e=e+(-1)|0;}a.v=a.v+c.t.length|0;f=0;a:{while(f<c.t.length){g=a.u;e=b+1|0;if(f<0)break a;if(f>=c.t.length)break a;g.data[b]=c.t.charCodeAt(f);f=f+1|0;b=e;}return a;}c=new Be;c.A=1;c.z=1;M(c);}c=new Be;c.A=1;c.z=1;M(c);},B$=(a,b,c,d)=>{let e,f,g,h,i,j,k;e=1;if(c<0){e=0;c= -c|0;}a:{if(BP(c,d)<0){if(e)BF(a,b,b+1|0);else{BF(a,b,b+2|
0);f=a.u.data;g=b+1|0;f[b]=45;b=g;}a.u.data[b]=BA(c,d);}else{h=1;i=1;j=Bw((-1),d);b:{while(true){k=BI(h,d);if(BP(k,c)>0){k=h;break b;}i=i+1|0;if(BP(k,j)>0)break;h=k;}}if(!e)i=i+1|0;BF(a,b,b+i|0);if(e)e=b;else{f=a.u.data;e=b+1|0;f[b]=45;}while(true){if(!k)break a;f=a.u.data;b=e+1|0;f[e]=BA(Bw(c,k),d);c=Dg(c,k);k=Bw(k,d);e=b;}}}return a;},Bx=(a,b)=>{let c,d,e,f,g,h;c=a.u.data;d=c.length;if(d>=b)return;if(d>=1073741823)e=2147483647;else{f=d*2|0;e=5;if(f>e)e=f;if(b>e)e=b;}g=G(e);if(e<d)d=e;h=g.data;b=0;while(b<
d){h[b]=c[b];b=b+1|0;}a.u=g;},Dt=a=>{let b,c,d,e,f;b=new H;c=a.u;d=c.data;e=a.v;f=d.length;if(e>=0&&e<=(f-0|0)){b.t=W(c.data,0,e);return b;}b=new S;b.A=1;b.z=1;M(b);},BF=(a,b,c)=>{let d,e,f,g;d=a.v;e=d-b|0;a.g((d+c|0)-b|0);f=e-1|0;while(f>=0){g=a.u.data;g[c+f|0]=g[b+f|0];f=f+(-1)|0;}a.v=a.v+(c-b|0)|0;},BQ=F(0),K=F(Bm),Bj=(a,b,c)=>{Z(a,b,c);return a;},C1=a=>{let b,c,d,e,f;b=new H;c=a.u;d=c.data;e=a.v;f=d.length;if(e>=0&&e<=(f-0|0)){b.t=W(c.data,0,e);return b;}b=new S;b.A=1;b.z=1;M(b);},CW=(a,b)=>{Bx(a,b);},C9
=(a,b,c)=>{Z(a,b,c);return a;};
function B9(){E.call(this);this.R=null;}
let BL=()=>{BL=B1(B9);CP();},CM=b=>{let c,d,e,f,g,h,i,j,k,l;BL();Br();if(I===null){c=new L;d=null;e=null;c.B=d;d=new K;Cb(d);d.u=G(16);c.w=d;c.C=G(32);c.y=0;c.x=e;I=c;}J("Service1 constructor");J("\n");c=new BU;c.F=Bc(E,10);c=c;BC(c,c.E+1|0);b=c.F.data;f=c.E;g=f+1|0;c.E=g;b[f]=D(2);c.H=c.H+1|0;BC(c,g+1|0);b=c.F.data;f=c.E;h=f+1|0;c.E=h;b[f]=D(3);c.H=c.H+1|0;BC(c,h+1|0);b=c.F.data;f=c.E;c.E=f+1|0;b[f]=D(4);c.H=c.H+1|0;if(I===null){d=new L;e=null;i=null;d.B=e;e=new K;e.u=G(16);d.w=e;d.C=G(32);d.y=0;d.x=i;I=d;}if
(I!==null){g=0;while(g<c.E){d=c.F.data[g];if(d===null)d=D(1);J(N(d));J("\n");g=g+1|0;}if(I===null){c=new L;d=null;e=null;c.B=d;d=new K;d.u=G(16);c.w=d;c.C=G(32);c.y=0;c.x=e;I=c;}c=new K;c.u=G(16);g=c.v;e=c;d=Dc(D(5));C9(e,g,d);B$(c,c.v,1,10);d=new H;b=c.u;j=b.data;k=c.v;f=j.length;if(k>=0&&k<=(f-0|0)){d.t=W(b.data,0,k);c=new K;c.u=G(16);g=c.v;i=c;l=D(6);e=i;Bj(e,g,l);Bj(e,c.v,d);Bj(e,c.v,D(7));Bj(e,c.v,D(8));d=new H;b=c.u;j=b.data;k=c.v;f=j.length;if(k>=0&&k<=(f-0|0)){d.t=W(b.data,0,k);c=new K;c.u=G(16);g=c.v;i
=c;l=D(9);e=i;Z(e,g,l);Z(e,c.v,d);d=new H;b=c.u;j=b.data;k=c.v;f=j.length;if(k>=0&&k<=(f-0|0)){d.t=W(b.data,0,k);J(N(d));J("\n");if(I===null){c=new L;d=null;e=null;c.B=d;d=new K;d.u=G(16);c.w=d;c.C=G(32);c.y=0;c.x=e;I=c;}f=C_(D(10),D(11));c=new Bm;c.u=G(20);c=(B$(c,c.v,f,10)).k();if(c===null)c=D(1);J(N(c));J("\n");if(I===null){c=new L;d=null;e=null;c.B=d;d=new K;d.u=G(16);c.w=d;c.C=G(32);c.y=0;c.x=e;I=c;}J("Bar");J("\n");if(I===null){c=new L;d=null;e=null;c.B=d;d=new K;d.u=G(16);c.w=d;c.C=G(32);c.y=0;c.x=e;I
=c;}J("Baz");J("\n");if(I===null){c=new L;d=null;e=null;c.B=d;d=new K;d.u=G(16);c.w=d;c.C=G(32);c.y=0;c.x=e;I=c;}if(D(12)!==D(12)){if(D(12) instanceof H){d=D(12);g=D(12).t!==d.t?0:1;}else g=0;}else g=1;if(!g){if(D(12)!==D(13)){if(D(13) instanceof H){d=D(13);g=D(12).t!==d.t?0:1;}else g=0;}else g=1;c=!g?null:new Q;}else c=new O;c=c.o();if(c===null)c=D(1);J(N(c));J("\n");if(I===null){c=new L;d=null;e=null;c.B=d;d=new K;d.u=G(16);c.w=d;c.C=G(32);c.y=0;c.x=e;I=c;}if(D(13)===D(12))g=1;else if(D(12) instanceof H){d
=D(12);g=D(13).t!==d.t?0:1;}else g=0;if(!g){if(D(13)!==D(13)){if(D(13) instanceof H){d=D(13);g=D(13).t!==d.t?0:1;}else g=0;}else g=1;c=!g?null:new Q;}else c=new O;c=c.o();if(c===null)c=D(1);J(N(c));J("\n");if(I===null){c=new L;d=null;e=null;c.B=d;d=new K;d.u=G(16);c.w=d;c.C=G(32);c.y=0;c.x=e;I=c;}if(D(12)===D(12))g=1;else if(D(12) instanceof H){d=D(12);g=D(12).t!==d.t?0:1;}else g=0;if(!g){if(D(12)!==D(13)){if(D(13) instanceof H){d=D(13);g=D(12).t!==d.t?0:1;}else g=0;}else g=1;c=!g?null:new Q;}else c=new O;c
=c.constructor;if(c!==null){e=c.classObject;if(e===null){e=new U;e.D=c;c.classObject=e;}}else e=null;if(e.G===null)e.G=R(e.D.$meta.name);c=e.G;if(c===null)c=D(1);J(N(c));J("\n");if(I===null){c=new L;d=null;e=null;c.B=d;d=new K;d.u=G(16);c.w=d;c.C=G(32);c.y=0;c.x=e;I=c;}if(D(13)!==D(12)){if(D(12) instanceof H){d=D(12);g=D(13).t!==d.t?0:1;}else g=0;}else g=1;if(!g){if(D(13)!==D(13)){if(!(D(13) instanceof H))g=0;else{d=D(13);g=D(13).t!==d.t?0:1;}}else g=1;c=!g?null:new Q;}else c=new O;c=c.constructor;if(c===null)e
=null;else{e=c.classObject;if(e===null){e=new U;e.D=c;c.classObject=e;}}if(e.G===null)e.G=R(e.D.$meta.name);c=e.G;if(c===null)c=D(1);J(N(c));J("\n");if(I===null){c=new L;d=null;e=null;c.B=d;d=new K;d.u=G(16);c.w=d;c.C=G(32);c.y=0;c.x=e;I=c;}if(D(13)===D(12))g=1;else if(D(12) instanceof H){d=D(12);g=D(13).t!==d.t?0:1;}else g=0;if(g)c=new O;else{if(D(13)===D(13))g=1;else if(!(D(13) instanceof H))g=0;else{d=D(13);g=D(13).t!==d.t?0:1;}c=!g?null:new Q;}J(N(!Cx(c,Bl)?D(14):D(15)));J("\n");if(I===null){c=new L;d=null;e
=null;c.B=d;d=new K;d.u=G(16);c.w=d;c.C=G(32);c.y=0;c.x=e;I=c;}if(D(13)!==D(12)){if(D(12) instanceof H){d=D(12);g=D(13).t!==d.t?0:1;}else g=0;}else g=1;if(!g){if(D(13)===D(13))g=1;else if(!(D(13) instanceof H))g=0;else{d=D(13);g=D(13).t!==d.t?0:1;}c=!g?null:new Q;}else c=new O;J(N(!(c instanceof O)?D(14):D(15)));J("\n");if(I===null){c=new L;d=null;e=null;c.B=d;d=new K;d.u=G(16);c.w=d;c.C=G(32);c.y=0;c.x=e;I=c;}if(D(13)!==D(12)){if(!(D(12) instanceof H))g=0;else{d=D(12);g=D(13).t!==d.t?0:1;}}else g=1;if(g)c=
new O;else{if(D(13)===D(13))g=1;else if(!(D(13) instanceof H))g=0;else{d=D(13);g=D(13).t!==d.t?0:1;}c=!g?null:new Q;}J(N(!(c instanceof Q)?D(14):D(15)));J("\n");if(I===null){c=new L;d=null;e=null;c.B=d;d=new K;d.u=G(16);c.w=d;c.C=G(32);c.y=0;c.x=e;I=c;}if(D(12)===D(12))g=1;else if(!(D(12) instanceof H))g=0;else{d=D(12);g=D(12).t!==d.t?0:1;}if(g)c=new O;else{if(D(12)===D(13))g=1;else if(!(D(13) instanceof H))g=0;else{d=D(13);g=D(12).t!==d.t?0:1;}c=!g?null:new Q;}J(N(!Cx(c,Bl)?D(14):D(15)));J("\n");if(I===null)
{c=new L;d=null;e=null;c.B=d;d=new K;d.u=G(16);c.w=d;c.C=G(32);c.y=0;c.x=e;I=c;}if(D(12)===D(12))g=1;else if(!(D(12) instanceof H))g=0;else{d=D(12);g=D(12).t!==d.t?0:1;}if(g)c=new O;else{if(D(12)===D(13))g=1;else if(!(D(13) instanceof H))g=0;else{d=D(13);g=D(12).t!==d.t?0:1;}c=!g?null:new Q;}J(N(!(c instanceof O)?D(14):D(15)));J("\n");if(I===null){c=new L;d=null;e=null;c.B=d;d=new K;d.u=G(16);c.w=d;c.C=G(32);c.y=0;c.x=e;I=c;}if(D(12)===D(12))g=1;else if(!(D(12) instanceof H))g=0;else{d=D(12);g=D(12).t!==d.t
?0:1;}if(g)c=new O;else{if(D(12)===D(13))g=1;else if(!(D(13) instanceof H))g=0;else{d=D(13);g=D(12).t!==d.t?0:1;}c=!g?null:new Q;}J(N(!(c instanceof Q)?D(14):D(15)));J("\n");return;}c=new S;B_(c);M(c);}c=new S;Cs(c);M(c);}c=new S;BT(c);M(c);}c=new BE;c.A=1;c.z=1;c.J=D(16);M(c);},CP=()=>{let b;BV=G(0);b=new H;b.t="";Cj=b;Ca=new Bq;Cg=Y(BO);Cf=Y(Bs);Cq=Bc(BM,128);b=new Bf;b.I=1;Cn=b;b=new Bf;b.I=0;Cl=b;Cw=Y(Cr);},Dn=F(),CY=(b,c)=>{let d,e,f,g,h,i,j,k,l;if(!b)return D(17);d=1<<c;e=d-1|0;f=(((32-Dj(b)|0)+c|0)-1
|0)/c|0;g=G(f);h=g.data;i=BI(f-1|0,c);j=0;while(i>=0){k=j+1|0;h[j]=BA((b>>>i|0)&e,d);i=i-c|0;j=k;}l=new H;l.t=W(g.data,0,h.length);return l;};
function BW(){E.call(this);this.P=0;}
let Br=()=>{Br=B1(BW);CD();},CD=()=>{let b,c,d;if(I===null){b=new L;c=null;d=null;b.B=c;c=new K;c.u=G(16);b.w=c;b.C=G(32);b.y=0;b.x=d;I=b;}J("Service1 static constructor");J("\n");},CJ=F();
function CI(){let a=this;E.call(a);a.T=null;a.U=null;}
let BS=F(0),Bt=F(0),Bu=F(),B5=F(0),Ch=F(0);
function Bz(){Bu.call(this);this.H=0;}
let Ci=F(0),B6=F(0);
function BU(){let a=this;Bz.call(a);a.F=null;a.E=0;}
let BC=(a,b)=>{let c,d,e,f,g,h,i,j,k;c=a.F;d=c.data;e=d.length;if(e<b){if(e>=1073741823)f=2147483647;else{g=e*2|0;f=5;if(g>f)f=g;if(b>f)f=b;}h=c.constructor;if(h===null)i=null;else{i=h.classObject;if(i===null){i=new U;i.D=h;h.classObject=i;}}j=i.D.$meta.item;if(j===null)h=null;else{h=j.classObject;if(h===null){h=new U;h.D=j;j.classObject=h;}}if(h===null){i=new BE;i.A=1;i.z=1;M(i);}if(h===Y(CG)){i=new Bp;i.A=1;i.z=1;M(i);}if(f<0){i=new Cu;i.A=1;i.z=1;M(i);}k=CS(h.D,f);if(f<e)e=f;b=0;while(b<e){k.data[b]=d[b];b
=b+1|0;}a.F=k;}},CQ=F(),I=null,CA=F(),Cd=F(0);
function C6(){E.call(this);this.Q=null;}
let Bl=F(0),O=F(),Dd=a=>{return D(12);},Q=F(O),CB=a=>{return D(13);},Cm=F(0),Bq=F(),BM=F(),Cf=null,Bb=null,Cq=null,X=null,Cp=(b,c)=>{let d,e;d=b.L.data;if(c<d.length)return c+d[c]|0;d=b.M;e=De(d,c);if(e>=0){d=d.data;e=e*2|0;if(e<d.length)return c+d[e+1|0]|0;}return 0;},De=(b,c)=>{let d,e,f,g;b=b.data;d=0;e=(b.length/2|0)-1|0;while(true){f=(d+e|0)/2|0;g=Di(b[f*2|0],c);if(!g)break;if(g<=0){d=f+1|0;if(d>e)return f;}else{e=f-1|0;if(e<d)return e;}}return f;},BA=(b,c)=>{if(c>=2&&c<=36&&b>=0&&b<c)return b<10?(48+b
|0)&65535:((97+b|0)-10|0)&65535;return 0;},DC=()=>{Cf=Y(Bs);Cq=Bc(BM,128);},Ck=()=>{return {"value":"TW  H#F#U 4%F#O #F#/ d%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #a1# #%# #%# #%# %%# #%# #%# #%# #%# #%# #%# #%# %%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #<+#%# #%# #%# \'.3#%# #%# #{1#%# #w1%%# %J\'#k1#o1#%# #w1#!3# #23#*3#%# \'23#:3# #>3#%# #%# #%# #N3#%# #N3# %%# #N3#%# #J3%%# #%# #R3#%# \'%# /)#%# #)#%# #)#%# #%# #%# #%# #%# #%# #%# #%# #%# %%# #%# #%# #%# #%# #%# #%# #%# #%# %)#%# #%# #8)#L%#%# #%# #%# #"
+"%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #a+# #%# #%# #%# #%# #%# #%# #%# #%# #%# /B45#%# #,/#645# %%# #P1#!\'#*\'#%# #%# #%# #%# #%# <-%# #%# \'%# 1&++ %_## #Z#)k%%g%% #F#W hA# 1%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# +]%# %%# #?#%# %a+\'N\'AF#b &#%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# 3%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #^#%# #%# #%# #%# #%# #%# #%# %%# #%# #%# #%# #%# #%# #%# #%"
+"# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# %*%r iB#oq-&# _?gejg#A1 a$#%# -mo%&# {-%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# 3,4/# #%# #%"
+"# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# 3C1 1C1 1C1 1C1 1C1 3C/ 1C1 QC1 1C1 1C1 1C%8\'%G# 7i\')G# 7C%D)\' 7C%u)%?# 7X+%P+%G# L-q*/# \'Pw/#8m/# -6## |bA G%# kC.#U !r*%&# &#%# #,05#qX\'#H.5# %%# #%# #%# #e25#D05#q25#m25# #%# %%# 1865%%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# "
+"#%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# 1%# #%# )%# (a=%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# G%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# y%%# #%# #%# #%# #%# #%# #%# \'%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #%# 5%# #%# #4Fd#%# #%# #%# #%# #%# )%# #<{p# %%# #%# \'%# #%# #%# #%# #%# #%# #%# #%# #%# #%# #P}p#}}p#m}p#D}p#P}p# #@yp#D{p#Lyp#Br#%# #%# #%"
+"# #%# #%# #%# #%# #%# #,%#L}p#LJd#%# #%# #$$r#%# \'%# +%# #%# #%# #P6rM \'%# ,T5F#U TUg#r {%g#r >\'c#p Lnk%F# .\'F#S HB#F#b o@5F#b Jo=N#f "};},BY=F(0),BX=F(0),Ct=F(0),BD=F();
function BG(){BD.call(this);this.B=null;}
function BB(){let a=this;BG.call(a);a.y=0;a.w=null;a.C=null;a.x=null;}
let BN=F(BB),L=F(BN),Bp=F(P),BE=F(P),S=F(P),CF=F();
function Bf(){E.call(this);this.I=0;}
let Cn=null,Cl=null,Cw=null,Dz=()=>{let b;b=new Bf;b.I=1;Cn=b;b=new Bf;b.I=0;Cl=b;Cw=Y(Cr);},CN=F(),Dw=F(),CK=F(),CS=(b,c)=>{if(b.$meta.primitive){switch(b){};}return Bc(b,c);},Cu=F(P),Dl=F(),Da=F(),Cv=b=>{let c,d,e,f,g,h,i,j,k,l;c=new Cc;d=G(b.t.length);e=d.data;f=0;g=e.length;while(true){if(f>=g){c.N=d;f=BK(c);d=B0(f*2|0);e=d.data;h=0;i=0;while(i<f){h=h+BK(c)|0;g=i*2|0;e[g]=h;j=g+1|0;k=BK(c);l=k/2|0;if(k%2|0)l= -l|0;e[j]=l;i=i+1|0;}return d;}if(f<0)break;if(f>=b.t.length)break;e[f]=b.t.charCodeAt(f);f=f+1
|0;}b=new Be;b.A=1;b.z=1;M(b);},B8=b=>{let c,d,e,f,g,h,i,j,k,l,m;c=B0(65536);d=c.data;e=0;f=0;g=0;a:{while(true){h=b.data;if(g>=h.length)break a;i=h[g];j=h[g+1|0];k=d.length;if(i<k)k=i;else if(i==e)break;if(e>k){l=new Bp;l.A=1;l.z=1;M(l);}while(e<k){m=e+1|0;d[e]=f;e=m;}g=g+2|0;e=k;f=j;}}l=new B4;l.M=b;l.L=c;return l;};
function B4(){let a=this;E.call(a);a.M=null;a.L=null;}
function Cc(){let a=this;E.call(a);a.N=null;a.K=0;}
let Dp=F(),BK=b=>{let c,d,e,f,g;c=0;d=1;while(true){e=b.N.data;f=b.K;b.K=f+1|0;g=e[f];g=g<34?g-32|0:g>=92?(g-32|0)-2|0:(g-32|0)-1|0;f=(g%2|0)!=1?0:1;c=c+BI(d,g/2|0)|0;d=d*46|0;if(!f)break;}return c;},Be=F(S);
Cz([-1,"js"]);
B7([E,0,0,[],0,3,0,0,0,BR,0,E,[],3,3,0,0,0,BZ,0,E,[],3,3,0,0,0,U,0,E,[BR,BZ],4,3,0,0,0,CU,0,E,[],4,3,0,0,0,Db,0,E,[],4,3,0,0,0,Bg,0,E,[],0,3,0,0,0,Bn,0,Bg,[],0,3,0,0,0,P,0,Bn,[],0,3,0,0,0,Dr,0,P,[],0,3,0,0,0,Ba,0,E,[],3,3,0,0,0,Bd,0,E,[],3,3,0,0,0,BH,0,E,[],3,3,0,0,0,H,0,E,[Ba,Bd,BH],0,3,0,0,0,By,0,E,[Ba],1,3,0,0,0,C2,0,By,[Bd],0,3,0,0,0,Bm,0,E,[Ba,BH],0,0,0,0,["g",B3(Bx),"k",Bi(Dt)],BQ,0,E,[],3,3,0,0,0,K,0,Bm,[BQ],0,3,0,0,["k",Bi(C1),"g",B3(CW)],B9,0,E,[],0,3,0,BL,0,Dn,0,E,[],4,3,0,0,0,BW,0,E,[],0,3,0,Br,0,CJ,
0,E,[],0,3,0,0,0,CI,0,E,[],0,3,0,0,0,BS,0,E,[],3,3,0,0,0,Bt,0,E,[BS],3,3,0,0,0,Bu,0,E,[Bt],1,3,0,0,0,B5,0,E,[Bt],3,3,0,0,0,Ch,0,E,[B5],3,3,0,0,0,Bz,0,Bu,[Ch],1,3,0,0,0,Ci,0,E,[],3,3,0,0,0,B6,0,E,[],3,3,0,0,0,BU,0,Bz,[Ci,Ba,B6],0,3,0,0,0,CQ,0,E,[],4,3,0,0,0,CA,0,E,[],4,3,0,0,0,Cd,0,E,[],3,3,0,0,0,C6,0,E,[Cd],0,3,0,0,0,Bl,0,E,[],3,3,0,0,0,O,"Bar",0,E,[Bl],0,3,0,0,["o",Bi(Dd)],Q,"Baz",0,O,[],0,3,0,0,["o",Bi(CB)],Cm,0,E,[],3,3,0,0,0,Bq,0,E,[Cm],0,3,0,0,0,BM,0,E,[Bd],0,3,0,0,0,BY,0,E,[],3,3,0,0,0,BX,0,E,[BY],3,3,
0,0,0,Ct,0,E,[],3,3,0,0,0,BD,0,E,[BX,Ct],1,3,0,0,0,BG,0,BD,[],0,3,0,0,0,BB,0,BG,[BQ],0,3,0,0,0,BN,0,BB,[],1,3,0,0,0]);
B7([L,0,BN,[],0,3,0,0,0,Bp,0,P,[],0,3,0,0,0,BE,0,P,[],0,3,0,0,0,S,0,P,[],0,3,0,0,0,CF,0,E,[Bd],1,3,0,0,0,Bf,0,E,[Ba,Bd],0,3,0,0,0,CN,0,E,[],4,3,0,0,0,Dw,0,E,[],0,3,0,0,0,CK,0,E,[],4,3,0,0,0,Cu,0,P,[],0,3,0,0,0,Dl,0,E,[],4,0,0,0,0,Da,0,E,[],4,3,0,0,0,B4,0,E,[],0,3,0,0,0,Cc,0,E,[],0,3,0,0,0,Dp,0,E,[],4,3,0,0,0,Be,0,S,[],0,3,0,0,0]);
let C7=Bk(Bs),Dk=Bk(BO);
C3(["<java_object>@","null","item1","item2","item3","Service","Service3: ",", ","Service2","Main:","HELLO","hello","Bar","Baz","false","true","","0"]);
H.prototype.toString=function(){return N(this);};
H.prototype.valueOf=H.prototype.toString;E.prototype.toString=function(){return N(Dh(this));};
E.prototype.__teavm_class__=function(){return C$(this);};
let C=CC(CM);
C.javaException=CH;
B.main=C;}));
this.main();